<a href="https://colab.research.google.com/github/janakimeena/Python-for-Data-Science/blob/master/Numpy_updated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
NumPy (Numerical Python) is a linear algebra library in Python. It is a very important library on which almost every data science or machine learning Python packages such as SciPy (Scientific Python), Mat−plotlib(plotting library), Scikit-learn, etc depends on to a reasonable extent.

NumPy is very useful for performing mathematical and logical operations on Arrays. It provides an abundance of useful features for operations on n-arrays and matrices in Python.

# Why NumPy when list is there


## NumPy arrays consume less memory than lists



In [0]:
import numpy as np
import sys
S = list(range(100000))
print(sys.getsizeof(100000)*len(S))
D = np.arange(100000)
print(D.size*D.itemsize)

2800000
800000


## NumPy arrays are faster than lists

In [0]:
import time
t1 = time.time()
X = range(100000)
Y = range(100000)
Z = [X[i] + Y[i] for i in range(len(X)) ]
print(time.time() - t1)

0.034543514251708984


In [0]:
import numpy as np

# Creating a NumPy array
Numpy array is created using array function in the package. The dimension of the array can be from one to many

In [0]:
one_D = np.array([1,2,3]) #one_D = np.array([(1,2,3)])
print(one_D)

[1 2 3]


In [0]:
two_D = np.array([[1,2,3],[4,5,6]]) #two_D = np.array([(1,2,3),(4,5,6)])
print(two_D)

[[1 2 3]
 [4 5 6]]


In [0]:
three_D = np.array([[(1,2,3),(4,5,6),(7,8,9)],[(11,12,13),(14,15,16),(17,18,19)]])
print(three_D)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


# Dimension of the array

In [0]:
import  numpy as np
a = np.array([(1,2,3),(4,5,6)])
print('Dimension\t',a.ndim)   # Dimension of array


Dimension	 2


In [0]:
print('Byte Size\t', a.itemsize) # Byte size of each element


Byte Size	 8


In [0]:
print('Data type\t',a.dtype) # Data type of elements in array


Data type	 int64


In [0]:
print('Size\t',a.size)


Size	 6


In [0]:
print('Shape\t',a.shape)

Shape	 (2, 3)


# Accessing elements of an array / Indexing in NumPy
One dimensional - one_D[2]

Two dimensional - two_D[1][2] or two_D[1,2]

Three dimensional - three_D[1][2][2] or three_D[1, 2, 2]

In [0]:
print(one_D[2])

3


In [0]:
print(two_D[1][2]) # print(two_D[1,2])

6


In [0]:
print(three_D[1][2][2])#print(three_D[1, 2, 2])

19


# Reshaping an array in NumPy
Reshape function is used to reshape arrays in NumPy

In [0]:
oneD = np.arange(1,25)

In [0]:
twoD = oneD.reshape(6,4)
print(twoD)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


# Ravel a 2D array

To get 1D array from a 2D array

In [0]:
new_OneD = np.ravel(twoD)
print(new_OneD)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## Reshape equivalent to Ravel

In [0]:
new_OneD1 = twoD.reshape(-1)
print(new_OneD1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


# Slicing in NumPy


In [0]:
two_D = np.arange(0,36).reshape(6,6)
sub = two_D[1:,3:6]
print(sub)


[[ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]


# Built-in Methods to Create NumPy Arrays
Certain built-in methods are available for creating NumPy arrays



1. arange function
2. Zeros
3. Ones
4. Eye
5. Linspace
6. Random Arrays



## Arange function

Generate a sequence of elements

In [0]:
# ten elements from 0 to 9
ten_ele = np.arange(0,10)
print(ten_ele)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
# odd numbers from 101 to 130
ten_ele = np.arange(101,130,2)
print(ten_ele)

[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]


## Create an array of zeros

In [0]:
# Array of 10 zeros
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
# 2D array of zeros
z2 = np.zeros((4,5))
print(z2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
# 3D array of zeros
z3 = np.zeros((4,5,2))
print(z3)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


## Creating array of ones

In [0]:
# by default elements are float can be changed by passing keyword arguments
o1 = np.ones(10,dtype=int)
print(o1)

[1 1 1 1 1 1 1 1 1 1]


## Identity Matrix
Identity matrices are very useful when dealing with linear algebras. Usually, is a two-dimensional square matrix. This means the number of row is equal to the number of column. One unique thing to note about identity matrix is that the diagonals are 1’s and everything else is 0. Identity matrices usually takes a single argument when a square matrix is required. But we can also give the dimension of row and column when a rectangular matrix is needed

In [0]:
e1 = np.eye(4,dtype=int)
print(e1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [0]:
# Identity matrix with '1' on the main diagonal
e1 = np.eye(4,5,dtype=int)
print(e1)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [0]:
# when k value is given then a matrix with '1' on the diagonal below the main diagonal
e1 = np.eye(4,5,k=-1,dtype=int)
print(e1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


##Linspace
linspace() function returns numbers evenly spaced over a specified intervals. Say we want 19 evenly spaced points from 1 to 10, we can easily use:

Unlike the arange() function which takes the third argument as the number of steps, linspace() takes the third argument as the number of datapoints to be created.

In [0]:
l1 = np.linspace(1,10,19)
print(l1)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [3]:
import numpy as np
l1 = np.linspace(1,10,19, retstep=True)
print(l1)

(array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ]), 0.5)


In [4]:
np.logspace(1,10,num=5,endpoint=True,base=10.0)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

## Generating an array of random numbers
An array of random numbers may be generated using rand(), randn() or randint() functions


1. random.rand() - generate an array of random numbers of the shape we pass to it from uniform distribution over 0 to 1
2. random.randn() - generate random samples from Standard, normal or Gaussian distribution centered around 0.
3. random.randint() - generate an array of integers. The randint() function can take up to 3 arguments; the low(inclusive), high(exclusive) and size of the array



In [0]:
# rand function
r1 = np.random.rand(4)
r2 = np.random.rand(3,4)
print('One Dimensional')
print(r1)
print('Two Dimensional')
print(r2)

One Dimensional
[0.8419345  0.34618812 0.54556492 0.4072628 ]
Two Dimensional
[[0.92545979 0.47831005 0.83585005 0.42175738]
 [0.38149602 0.915809   0.03628559 0.87760716]
 [0.83154596 0.90225047 0.73019777 0.41785007]]


In [0]:
# randn function 
# When we plot the result will give us a normal distribution curve.
r1 = np.random.randn(4)
r2 = np.random.randn(3,4)
print('One Dimensional')
print(r1)
print('Two Dimensional')
print(r2)

One Dimensional
[ 0.44693472 -0.10836244  0.06554634  1.02587854]
Two Dimensional
[[-0.06316557  0.20985433 -0.06519823 -0.3117963 ]
 [ 0.33031695  0.21268525 -0.81763227  1.04246474]
 [-0.60313155 -0.2624894   0.36918806  1.12858338]]


In [0]:
np.random.randint(20) #generates a random integer exclusive of 20

8

In [0]:
np.random.randint(2, 20) #generates a random integer including 2 but excluding 20

2

In [0]:
np.random.randint(2, 20, 7) #generates 7 random integers including 2 but excluding 20

array([16,  6, 19, 12,  5, 15, 11])

# Arithmetic Operations
Numerical operators are defined in NumPy to do basic arithmetic operation elementwise

In [0]:
a = np.array([(1,2,3,4,5,6)])
b = np.array([(0.5,1,1.5,2,2.5,3)])
print('Addition')
print(a+b)
print('Subtraction')
print(a-b)
print('Multiplication')
print(a*b)
print('Division')
print(a/b)

Addition
[[1.5 3.  4.5 6.  7.5 9. ]]
Subtraction
[[0.5 1.  1.5 2.  2.5 3. ]]
Multiplication
[[ 0.5  2.   4.5  8.  12.5 18. ]]
Division
[[2. 2. 2. 2. 2. 2.]]


# Add aan integer to a numpy array

In [0]:
e = a+50 #This adds 50 to every element in that array
print(e)

[[51 52 53 54 55 56]]


# Mathematical functions
Mathematical functions are also applied for each element of the numpy array

In [0]:
sr = np.sqrt(a)     #Returns the square root of each element
print(sr)

[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]]


In [0]:
ex = np.exp(a)     #Returns the exponentials of each element
print(ex)

[[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
  403.42879349]]


In [0]:
arr = np.array([1, 2, 3, 9])
s = np.sin(arr)     #Returns the sin of each element
print(s)

[0.84147098 0.90929743 0.14112001 0.41211849]


In [0]:
arr = np.array([1, 2, 3, 9])
s = np.cos(arr)     #Returns the sin of each element
print(s)

[ 0.54030231 -0.41614684 -0.9899925  -0.91113026]


In [0]:
arr = np.array([1, 2, 3, 9])
s = np.log(arr)     #Returns the sin of each element
print(s)

[0.         0.69314718 1.09861229 2.19722458]


In [0]:
arr = np.array([1, 2, 3, 9])
s = np.sum(arr)     #Returns the sin of each element
print(s)

15


In [0]:
arr = np.array([1, 2, 3, 9])
s = np.std(arr)     #Returns the sin of each element
print(s)

3.112474899497183


# Sum of elements in 2D Array

In [0]:
twoD.sum()         #Returns the sum of all the values in twoD

300

In [0]:
twoD.sum(axis=0) #Returns the sum of all the columns in mat

array([66, 72, 78, 84])

In [0]:
twoD.sum(axis=1) #Returns the sum of all the rows in mat

array([10, 26, 42, 58, 74, 90])

# Maximum and Minimum elements

max() and min() functions are used to find maximum and minimum value in the array

argmax() and argmin() functions are used to find index of the highest and index of the smallest element in the array

In [0]:
print(twoD)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [0]:
twoD.max()

24

In [0]:
twoD.min()

1

In [0]:
twoD.argmax()

23

In [0]:
twoD.argmin()

0

# Stacking of Arrays in NumPy
We can either horizontally or vertically stack an array into another array

1.   To horizontally stack - hstack () function is used
2.   To vertically stack - vstack () function is used



In [0]:
# add along x axis, number of rows should be same
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(0.5,1,1.5),(2,2.5,3)])
print('After HStacking')
print(np.hstack((a,b)))

After HStacking
[[1.  2.  3.  0.5 1.  1.5]
 [4.  5.  6.  2.  2.5 3. ]]


In [0]:
# add along y axis, number of colums should be same
print('After VStacking')
print(np.vstack((a,b)))


After VStacking


NameError: ignored

In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = np.insert(a,1,[10,11,12],axis=0)
print(a)

[[ 1  2  3]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]


In [10]:
a_del = np.delete(a,2,axis=0)
print(a_del)

[[ 1  2  3]
 [10 11 12]
 [ 7  8  9]]


# Create matrices in NumPy
A built-in function matrix is in NumPy

In [12]:
mat1 = np.matrix('1 2; 3 4')
print(mat1)

[[1 2]
 [3 4]]


In [21]:
mat2 = np.matrix('5 6; 7 8')
print(mat2)

[[5 6]
 [7 8]]


In [0]:
print(mat1+mat2)#element-wise multiplication

[[ 6  8]
 [10 12]]


In [22]:
np.dot(mat1,mat2) # matrux multiplication

matrix([[19, 22],
        [43, 50]])

In [0]:
print(mat1-mat2)

[[-4 -4]
 [-4 -4]]


In [0]:
print(mat1*mat2)

[[19 22]
 [43 50]]


In [24]:
mat_tra = np.transpose(mat1)
mat_tra

matrix([[1, 3],
        [2, 4]])

In [25]:
mat_div = np.divide(mat1,mat2)
print(mat_div)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [13]:
print(mat1.shape)

(2, 2)


In [14]:
print(mat1.size)

4


In [18]:
col_new=np.matrix("10,11")
mat_ins = np.insert(mat1,0,col_new,axis=1)
print(mat_ins)

[[10  1  2]
 [11  3  4]]


In [19]:
row_new = np.matrix('22,23,24')
mat_ins = np.insert(mat_ins,0,row_new,axis=0)
print(mat_ins)

[[22 23 24]
 [10  1  2]
 [11  3  4]]


In [0]:
import time
t1 = time.time()
X = np.arange(100000)
Y = np.arange(100000)
Z = X + Y
print(time.time() - t1)


0.0042438507080078125


## Linear Algebra

numpy.linalg.det() - Returns determinant of a matrix

In [0]:
m1 = np.matrix('4, 5, 16, 7; 2, -3, 2, 3; 3, 4, 5, 6; 4, 7, 8, 9')

In [30]:
print(np.linalg.det(m1))

128.00000000000009


In [31]:
np.linalg.matrix_rank(m1)

4

In [32]:
print(np.linalg.inv(m1))

[[ 9.37500000e-02 -4.68750000e-01  3.68750000e+00 -2.37500000e+00]
 [ 1.00929366e-16 -2.50000000e-01  5.00000000e-01 -2.50000000e-01]
 [ 9.37500000e-02  3.12500000e-02 -3.12500000e-01  1.25000000e-01]
 [-1.25000000e-01  3.75000000e-01 -1.75000000e+00  1.25000000e+00]]


In [0]:
# Solving System of Linear Equations
'''3x+y+2z=2
3x+2y+5z=-1
6x+7y+8z=3'''
A = np.matrix('3, 1, 2; 3, 2, 5; 6, 7, 8' )
#X = (x, y, z)
B = np.matrix('2;-1;3')
X =  np.linalg.solve(A,B)


In [35]:
print(X)

[[ 1.24242424]
 [ 0.81818182]
 [-1.27272727]]
